name: Docker and Kubernetes Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t final-project:latest .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Running application tests..."

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kubernetes Deployment
        run: echo "Deploying application to Kubernetes..."

      - name: Check Kubernetes
        run: kubectl version --client
